# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.14.0
      with:
        settings-servers: |
          [{
            "id": "github-thenestruo-parent",
            "username": "theNestruo",
            "password": "${{ secrets.THENESTRUO_PARENT_PASSWORD }}"
          }]
        settings-repositories: |
          [{
            "id": "github-thenestruo-parent",
            "url": "https://maven.pkg.github.com/theNestruo/thenestruo-parent"
          }]

    - name: Build with Maven
      run: mvn -B verify --file pom.xml
