name: Verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        settings-servers: |
          [{
            "id": "github-thenestruo-parent",
            "username": "theNestruo",
            "password": "${{ secrets.THENESTRUO_PARENT_PASSWORD }}"
          }]
        settings-repositories: |
          [{
            "id": "github-thenestruo-parent",
            "url": "https://maven.pkg.github.com/theNestruo/thenestruo-parent"
          }]

    - name: Verify
      run: mvn --batch-mode verify
